package sitemap_generator;

// import the necessary packages
import java.io.*;
import java.util.*;
import java.text.*;

public class SitemapBuilder
{
	// Config object associated with the configuration of the sitemap
	// to be built
	private Config config = null;
	// OrganizationPersonBuilder used to build the list of OrganizationPerson
	// objects and search through them
	private OrganizationPersonBuilder opBuilder = null;
	// List of files in the sitemap
	private LinkedList<String> sitemapFiles = new LinkedList<String>();
	// List of OrganizationPerson objects
	private ArrayList<OrganizationPerson> opList = null;
	// List of Rating objects
	private ArrayList<Rating> ratingList = null;
	// current date of when the sitemap is being generated
	private String currentDate = null;
	
	public SitemapBuilder(String configPath) throws IOException
	{
		// build the configuration
		this.config = new Config(configPath);

		// build the OrganizationPerson object list
		this.opBuilder = new OrganizationPersonBuilder(this.config.getOption("org_person_dump_path"));
		this.opList = opBuilder.build();
			
		// build the Rating object list
		RatingBuilder ratingBuilder = new RatingBuilder(config.getOption("rating_dump_path"));
		this.ratingList = ratingBuilder.build();

		// grab the current date
		DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
		Date date = new Date();
		this.currentDate = dateFormat.format(date);
	}
	
	public void build() throws IOException
	{
		// determine which sitemaps are to be generated by examining the
		// configuration
		boolean useOrgs = Boolean.parseBoolean(this.config.getOption("generate_org_sitemap"));
		boolean usePersons = Boolean.parseBoolean(this.config.getOption("generate_person_sitemap"));
		boolean usePersonReviews = Boolean.parseBoolean(this.config.getOption("generate_person_review_sitemap"));
		boolean useRatings = Boolean.parseBoolean(this.config.getOption("generate_rating_sitemap"));
		
		// check to see if the organization sitemap should be generated
		if (useOrgs)
		{
			// build the organization sitemap
			this.buildOrgSitemap();
		}
		
		// check to see if the person sitemap should be generated
		if (usePersons)
		{
			// build the person sitemap
			this.buildPersonSitemap();
		}
		
		// check to see if the person review sitemap should be generated
		if (usePersonReviews)
		{
			// build the person review sitemap
			this.buildPersonReviewSitemap();
		}
		
		// check to see if the rating sitemap should be generated
		if (useRatings)
		{
			// build the rating sitemap
			this.buildRatingSitemap();
		}
		
		// build the sitemap index now that the URL sets have been
		// generated
		this.buildSitemapIndex();
	}
	
	private void buildOrgSitemap() throws IOException
	{
		// initialize the URLSetWriter, the Iterator used to loop over
		// the OrganizationPerson objects, and the Set used to determine
		// if an organization has already been examined or not
		URLSetWriter writer = null;
		Iterator<OrganizationPerson> iter = this.opList.iterator();
		Set<Integer> orgIDs = new HashSet<Integer>();
		
		// initialize the current sitemap filename, the current sitemap file
		// number, the number of nodes inspected thus far, and the number
		// of nodes actually written to the sitemap
		String filename = null;
		int fileNum = 1;
		int count = 0;
		int numWritten = 0;
		
		// loop over the OrganizationPerson list
		while (iter.hasNext())
		{
			// if the writer is null, then open a file for it to write to
			if (writer == null)
			{
				// construct the filename
				filename = "/sitemap_" + this.config.getOption("org_sitemap_called") + "_";
				filename += this.config.getOption("country_code") + "_" + fileNum + "_";
				filename += this.currentDate + ".xml";
								
				// construct the writer
				writer = new URLSetWriter(this.config.getOption("sitemap_output_path") + filename);
			}
			
			// grab the next OrganizationPerson node
			OrganizationPerson node = iter.next();
			
			// check to see if the node belongs to the country ID in the
			// configuration
			if (node.getCountryID() == Integer.parseInt(this.config.getOption("country_id")))
			{
				// only write the organization to file if we have not
				// already seen the ID
				if (!orgIDs.contains(node.getOrgID()))
				{
					// construct the URL to be written to file
					String url = "http://" + this.config.getOption("root_site");
					url += node.getOrgURL();
				
					// write the block to file and update the Set of organization
					// IDs that we have seen thus far
					writer.writeBlock(url, this.currentDate, this.config.getOption("change_freq"), this.config.getOption("priority"));
					orgIDs.add(node.getOrgID());
					
					// increment the number of nodes written to file
					numWritten++;
				}
			}
			
			// check to see if the current sitemap file should be closed
			if (numWritten != 0 && (numWritten % Integer.parseInt(this.config.getOption("num_items_per_urlset")) == 0 || count + 1 == this.opList.size()))
			{
				// close the writer and set it to null
				writer.close();
				writer = null;
				
				// compress the sitemap store the compressed sitemap file path
				String cmd = "gzip " + this.config.getOption("sitemap_output_path") + "/" + filename;
				Runtime.getRuntime().exec(cmd);
				this.sitemapFiles.add(filename + ".gz");
				
				// increment the total number of organization sitemap files
				fileNum++;
			}
			
			// increment the number of nodes insepected
			count++;
		}
	}
	
	private void buildPersonSitemap() throws IOException
	{
		// initialize the URLSetWriter and the Iterator used to loop over
		// the OrganizationPerson objects
		URLSetWriter writer = null;
		Iterator<OrganizationPerson> iter = this.opList.iterator();
		
		// initialize the current sitemap path, the current sitemap file
		// number, the number of nodes inspected thus far, and the number
		// of nodes actually written to the sitemap
		String filename = null;
		int fileNum = 1;
		int count = 0;
		int numWritten = 0;
		
		// loop over the OrganizationPerson list
		while (iter.hasNext())
		{
			// if the writer is null, then open a file for it to write to
			if (writer == null)
			{
				// construct the filename
				filename = "/sitemap_" + this.config.getOption("person_sitemap_called") + "_";
				filename += this.config.getOption("country_code") + "_" + fileNum + "_";
				filename += this.currentDate + ".xml";
								
				// construct the writer
				writer = new URLSetWriter(this.config.getOption("sitemap_output_path") + filename);
			}
			
			// grab the next OrganizationPerson node
			OrganizationPerson node = iter.next();
			
			// check to see if the node belongs to the country ID in the
			// configuration
			if (node.getCountryID() == Integer.parseInt(this.config.getOption("country_id")))
			{
				// construct the URL to be written to file
				String url = "http://" + this.config.getOption("root_site");
				url += node.getPersonURL();
				
				// write the block to file
				writer.writeBlock(url, this.currentDate, this.config.getOption("change_freq"), this.config.getOption("priority"));
					
				// increment the number of nodes written to file
				numWritten++;
			}
			
			// check to see if the current sitemap file should be closed
			if (numWritten != 0 && (numWritten % Integer.parseInt(this.config.getOption("num_items_per_urlset")) == 0 || count + 1 == this.opList.size()))
			{
				// close the writer and set it to null
				writer.close();
				writer = null;
				
				// compress the sitemap store the compressed sitemap file path
				String cmd = "gzip " + this.config.getOption("sitemap_output_path") + "/" + filename;
				Runtime.getRuntime().exec(cmd);
				this.sitemapFiles.add(filename + ".gz");
				
				// increment the total number of organization sitemap files
				fileNum++;
			}
			
			// increment the number of nodes insepected
			count++;
		}
	}

	private void buildPersonReviewSitemap() throws IOException
	{
		// initialize the URLSetWriter and the Iterator used to loop over
		// the OrganizationPerson objects
		URLSetWriter writer = null;
		Iterator<OrganizationPerson> iter = this.opList.iterator();
		
		// initialize the current sitemap path, the current sitemap file
		// number, the number of nodes inspected thus far, and the number
		// of nodes actually written to the sitemap
		String filename = null;
		int fileNum = 1;
		int count = 0;
		int numWritten = 0;
		
		// loop over the OrganizationPerson list
		while (iter.hasNext())
		{
			// if the writer is null, then open a file for it to write to
			if (writer == null)
			{
				// construct the filename
				filename = "/sitemap_" + this.config.getOption("person_review_sitemap_called") + "_";
				filename += this.config.getOption("country_code") + "_" + fileNum + "_";
				filename += this.currentDate + ".xml";
								
				// construct the writer
				writer = new URLSetWriter(this.config.getOption("sitemap_output_path") + filename);
			}
			
			// grab the next OrganizationPerson node
			OrganizationPerson node = iter.next();
			
			// check to see if the node belongs to the country ID in the
			// configuration
			if (node.getCountryID() == Integer.parseInt(this.config.getOption("country_id")))
			{
				// extract the organization name porition of the URL
				int pos = node.getOrgURL().indexOf("/", 1);
				String orgName = node.getOrgURL().substring(0, pos);

				// extract usable URL portion of the person
				pos = node.getPersonURL().lastIndexOf("-");
				String personURL = node.getPersonURL().substring(0, pos + 1);
				
				// construct the URL for the person review
				String url = "http://" + this.config.getOption("root_site");
				url += orgName + personURL + "req";
				
				// write the block to file
				writer.writeBlock(url, this.currentDate, this.config.getOption("change_freq"), this.config.getOption("priority"));
					
				// increment the number of nodes written to file
				numWritten++;
			}
			
			// check to see if the current sitemap file should be closed
			if (numWritten != 0 && (numWritten % Integer.parseInt(this.config.getOption("num_items_per_urlset")) == 0 || count + 1 == this.opList.size()))
			{
				// close the writer and set it to null
				writer.close();
				writer = null;
				
				// compress the sitemap store the compressed sitemap file path
				String cmd = "gzip " + this.config.getOption("sitemap_output_path") + "/" + filename;
				Runtime.getRuntime().exec(cmd);
				this.sitemapFiles.add(filename + ".gz");
				
				// increment the total number of organization sitemap files
				fileNum++;
			}
			
			// increment the number of nodes insepected
			count++;
		}
	}
	
	private void buildRatingSitemap() throws IOException
	{
		// initialize the URLSetWriter and the Iterator used to loop over
		// the Rating objects
		URLSetWriter writer = null;
		Iterator<Rating> iter = this.ratingList.iterator();
		
		// initialize the current sitemap path, the current sitemap file
		// number, the number of nodes inspected thus far, and the number
		// of nodes actually written to the sitemap
		String filename = null;
		int fileNum = 1;
		int count = 0;
		int numWritten = 0;
		
		// loop over the Rating list
		while (iter.hasNext())
		{
			// if the writer is null, then open a file for it to write to
			if (writer == null)
			{
				// construct the filename
				filename = "/sitemap_" + this.config.getOption("rating_sitemap_called") + "_";
				filename += this.config.getOption("country_code") + "_" + fileNum + "_";
				filename += this.currentDate + ".xml";
								
				// construct the writer
				writer = new URLSetWriter(this.config.getOption("sitemap_output_path") + filename);
			}
			
			// grab the next Rating node and use it to find the corresponding
			// OrganizatonPerson node that it belongs to
			Rating ratingNode = iter.next();
			OrganizationPerson opNode = this.opBuilder.find(ratingNode.getPersonID());

			// check to see if the node belongs to the country ID in the
			// configuration
			if (opNode.getCountryID() == Integer.parseInt(this.config.getOption("country_id")))
			{
				// construct the URL to be written to file
				String url = "http://" + this.config.getOption("root_site");
				url += ratingNode.getRatingURL();
				
				// write the block to file
				writer.writeBlock(url, this.currentDate, this.config.getOption("change_freq"), this.config.getOption("priority"));
					
				// increment the number of nodes written to file
				numWritten++;
			}
			
			// check to see if the current sitemap file should be closed
			if (numWritten != 0 && (numWritten % Integer.parseInt(this.config.getOption("num_items_per_urlset")) == 0 || count + 1 == this.ratingList.size()))
			{
				// close the writer and set it to null
				writer.close();
				writer = null;
				
				// compress the sitemap store the compressed sitemap file path
				String cmd = "gzip " + this.config.getOption("sitemap_output_path") + "/" + filename;
				Runtime.getRuntime().exec(cmd);
				this.sitemapFiles.add(filename + ".gz");
				
				// increment the total number of organization sitemap files
				fileNum++;
			}
			
			// increment the number of nodes insepected
			count++;
		}
	}
	
	private void buildSitemapIndex() throws IOException
	{
		// construct the SitemapIndexWriter
		String path = this.config.getOption("sitemap_output_path") + "/";
		path += this.config.getOption("sitemap_index_filename");
		SitemapIndexWriter writer = new SitemapIndexWriter(path);
		Iterator<String> iter = this.sitemapFiles.iterator();
		
		// loop over the sitemap files
		while (iter.hasNext())
		{
			// construct the URL and write each block to file
			String url = "http://" +  this.config.getOption("root_site") + "/";
			url += this.config.getOption("sitemap_directory") + iter.next();
			writer.writeBlock(url, this.currentDate);
		}
		
		// close the writer
		writer.close();
	}
	
	public static void main(String args[])
	{
		// try to build the sitemaps
		try
		{
			int enumPaths = 0;
			
			// print warning information to the user
			System.out.println("NOTE: IF YOU ARE GENERATING A SITEMAP THAT USES THE");
			System.out.println("PERSON REVIEW URL, THEN THE FOLLOWING METHOD NEEDS TO");
			System.out.println("BE MODIFIED TO ENSURE THAT IT GENERATES THE URL CORRECTLY:");
			System.out.print("\n\tprivate void buildPersonReviewSitemap()\n\n");
			System.out.println("FAILING TO MODIFY HOW THE PERSON REVIEW URL IS");
			System.out.println("CONSTRUCTED COULD RESULT IN INVALID SITEMAPS.\n");
			System.out.println("GENERATING SITEMAPS:");
			
			// loop over the supplied configuration file paths
			for (enumPaths = 0; enumPaths < args.length; enumPaths++)
			{
				// print diagnostic information to the user
				System.out.println("[x] generating sitemap using '" + args[enumPaths] + "'");

				// build the sitemap
				SitemapBuilder sitemapBuilder = new SitemapBuilder(args[enumPaths]);
				sitemapBuilder.build();
			}
		}
		
		// catch any exceptions that occur
		catch (Exception exception)
		{
			// print the exception information
			System.out.println("exception: " + exception.getMessage());
			exception.printStackTrace();
		}
	}
}