<?php

/**
 * @ingroup core
 * @file core.php
 *
 * @brief
 * Core rating platform configuration file.
 *
 * This file is the core rating platform configuration file that
 * defines the basic configurations to run the site.
 *
 * DO NOT EDIT THIS FILE. THIS IS THE CORE CONFIGURATION FILE ALL
 * EDITS AND EXTENSIONS SHOULD BE ADDED TO THE 'site.php' FILE.
 *
 * @author Adrian Rosebrock
 */

/**
 * Initialize the core configuration dictionary.
 */
$config = array();
/**
 * Initialize the core constants dictionary.
 */
$config["core.constants"] = array();
/**
 * Initialize the core URL trailers dictionary.
 */
$config["core.url.trailers"] = array();
/**
 * Initialize the core classes dictionary.
 */
$config["core.classes"] = array();



/**
 * Define the displayable site name.
 */
$config["core.sitename"] = "RateMySomething.com";



/**
 * Define the base URL of the site
 */
$config["core.base_url"] = "http://localhost:8888";



/**
 * Define the country ID of the site.
 */
$config["core.constants"]["country_id"] = 0;



/**
 * Define the country code string of the site.
 */
$config["core.constants"]["country_code"] = "us";



/**
 * Define the mapping of filters so persons can be filtered
 * or an organization page.
 */
$config["core.constants"]["filter_person_mappings"] = array(
	"Name" => "LastName",
	"Department" => "Department");
/**
 * Define the minimum status of a person to be displayed in
 * the persons list on the organization page.
 */
$config["core.constants"]["min_person_status"] = -2;
/**
 * Define the number of persons per page on the organization's
 * persons list.
 */
$config["core.constants"]["persons_per_page"] = 10;



/**
 * Define the minimum status for the user to be valid.
 */
$config["core.constants"]["min_user_status"] = 1;



/**
 * Define the maximum number of characters for the comment
 * field when adding a rating.
 */
$config["core.constants"]["max_rating_comment_chars"] = 200;
/**
 * Define the maximum number of characters for the comment
 * field when adding a rebuttal.
 */
$config["core.constants"]["max_rebuttal_comment_chars"] = 200;
/**
 * Define the minumum rating status for a rating to be displayed
 * on the person page.
 */
$config["core.constants"]["min_rating_status"] = -2;
/**
 * Define the number of ratings to display per page on the
 * person page.
 */
$config["core.constants"]["ratings_per_page"] = 5;
/**
 * Define the minimum amount of time that must pass between
 * a user adding ratings.
 */
$config["core.constants"]["min_rating_time_interval"] = "5 MINUTE";
/**
 * Define the minimum rebuttal status for a rebuttal to be
 * displayed on a rating page.
 */
$config["core.constants"]["min_rebuttal_status"] = -2;
/**
 * define the minimum amount of time that must pass between
 * a user adding rebuttals.
 */
$config["core.constants"]["min_rebuttal_time_interval"] = "5 MINUTE";



/**
 * Define the maximum number of characters that can be
 * entered in the reason field when flagging a rating
 * or a rebuttal.
 */
$config["core.constants"]["max_flag_reason_chars"] = 200;



/**
 * Define the anonymous (non-loggedin) user ID.
 */
$config["core.constants"]["anon_user_id"] = 1;



/**
 * Define the URL trailer for organizations.
 */
$config["core.url.trailers"]["Organizations"] = "o";
/**
 * Define the URL trailer for the person page.
 */
$config["core.url.trailers"]["People"] = "p";
/**
 * Define the URL trailer for the page where users can choose
 * between adding a rating and reviewing a person.
 */
$config["core.url.trailers"]["PeopleRequest"] = "req";
/**
 * Define the URL trailer for the page where users can add
 * a rating.
 */
$config["core.url.trailers"]["PeopleRate"] = "rate";
/**
 * Define the URL trailer for the rating page.
 */
$config["core.url.trailers"]["Ratings"] = "r";
/**
 * Define the URL trailer for the page where users can
 * flag ratings.
 */
$config["core.url.trailers"]["FlagRatings"] = "fra";
/**
 * Define the URL trailer for the page where users can
 * flag rebuttals.
 */
$config["core.url.trailers"]["FlagRebuttals"] = "fre";



/**
 * Define the class used when building organizations.
 *
 * @see organization.php
 */
$config["core.classes"]["Organization"] = "Organization";
/**
 * Define the class used when building persons.
 *
 * @see person.php
 */
$config["core.classes"]["People"] = "Person";
/**
 * Define the class used when building ratings.
 *
 * @see rating.php
 */
$config["core.classes"]["Rating"] = "Rating";
/**
 * Define the class used when building rebuttals.
 *
 * @see rebuttal.php
 */
$config["core.classes"]["Rebuttal"] = "Rebuttal";

?>