CREATE TABLE  `FlaggedRatings` (
`FID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`RID` INT NOT NULL ,
`PID` INT NULL ,
`FIP` TEXT NOT NULL ,
`FReason` TEXT NOT NULL ,
`FStamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
INDEX (  `RID` )
) ENGINE = INNODB;